### ISSUE TITLE
Not using GPU properly?

### ISSUE THREAD

**Issue by giodude12** [Sentdex/GANTheftAuto#7]
Hi, i got Gan Theft Auto to launch just fine, but it runs at 1 Frame a second. I figured it was because it wasn't properly detecting my GPU, and I found this:

```
2021-06-19 20:31:56.833152: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-06-19 20:31:56.833248: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
```

I tried everything and I'm not sure what could still be causing this? I have CUDA toolkit installed.

**Comment by giodude12** [comment]
oh hey i fixed it, it was cudnn that was required to make it work. However, now it stutters constantly and crashes when not in focus. This is on a 2080ti

**Comment by daniel-kukiela** [comment]
If you're on Windows (not sure about MacOS and Linux), focus cmd window and not OpenCV window (the one showing the output). If OpenCV window is focused, it stops updating if you press a key for longer.
I'm not sure about "crashed when not in focus". What does this mean? I can run it in the background and it works just ok. Or if you are pressing the `e` key - it tries to exit which may take a while or crash.
